---
title: "7. Symmetry, Isometries, and Frieze Patterns"
---

## Learning Goals

- Use distance and midpoint formulas.
- Compute slope and determine parallel/perpendicular lines.
- Connect algebraic and geometric representations.

## Formulas

Distance between $(x_1, y_1)$ and $(x_2, y_2)$:

$$
d = \sqrt{(x_2 - x_1)^2 + (y_2 - y_1)^2}
$$

Midpoint:

$$
M = \left(\frac{x_1 + x_2}{2}, \frac{y_1 + y_2}{2}\right)
$$

## Practice

1. Find distance between $(2, -1)$ and $(8, 7)$.
2. Determine if two lines are parallel.
3. Find equation of a line through two points.

## Art and Design Connections

- Recreate a minimalist poster on a coordinate grid and use midpoint and slope to align major elements.
- Design a line-art cityscape where parallel and perpendicular lines are controlled by slope constraints.
- Build a logo from plotted points and justify spacing using distance formula calculations.

## Creative Assignment

### Creative Assignment for this Chapter

(**Creative Homework Assignment #6: Isometry**)

Your sixth creative assignment is to create an original piece of art that involves an isometry.


- So many possibilities for this one: you do not have to create a frieze pattern but you are definitely welcome to do one. You can submit an assignment that has one isometry or more. It is up to you.
- it can be multiple conic sections or 
- it can be one type of conic section many times! 

You can decide which of these three options. You can do this in any way you want.

### Examples and More Information

* See the module folder on our course site for examples that would get credit and bonus for this creative homework assignment.
* For information on how these assignments work; the grading rubric; and the voting you can look in Chapter 9 of this textbook or many places on our course site!
* The more effort you put in for these assignments, the more bonus you get on exams. It helps if you write how long it took you to complete your work and how you created your assignment.

## Exercises

### Exercises for this Chapter

* Make sure you are logged into your FIT Google account or else you will not view the link below.
* Once you have your answers, submit them carefully through our course site on Brightspace by the deadline.

*The above are the Textbook Exercises for my MA142 students.*

### More Exercises

*These questions are for anyone! They are not required for my students.*

## Further Reading and Interactive Activities

* [Introduction to Transformations](https://mathigon.org/course/transformations/introduction)
* [Rigid Transformations](https://mathigon.org/course/transformations/rigid)
* [Symmetry](https://mathigon.org/course/transformations/symmetry)
* [Symmetry Groups & Wallpapers](https://mathigon.org/course/transformations/symmetry-groups)
* [Symmetry in Physics](https://mathigon.org/course/transformations/physics)
* [Dilations](https://mathigon.org/course/transformations/dilations)
