---
title: "8. Conic Sections"
---

## Learning Goals

- Describe conic sections.
- Define cylinder, cone, sphere, ellipse, parabola, hyperbola, circle.
- Compute using the volume formula for cylinders.
- Compute using the volume formula for cones.
- Compute using the volume formula for spheres.
- Compute using the surface area formula for cylinders.
- Compute using the surface area formula for cones.
- Compute using the surface area formula for spheres.
- Describe Planetary Orbits.
- Defy Gravity. (Just Kidding) instead we will Define Gravity.
- Recognize the contributions of Isaac Newton, Hypatia, and Kepler in relation to Conic Sections.

## Key Terms and Formulas

A translation by vector $\langle a, b \rangle$ sends:

$$
(x, y) \to (x + a, y + b)
$$

## Mini-Lecture

Transformations describe how figures move on the coordinate plane while preserving or changing size in predictable ways. By applying transformation rules step by step, you can map original points to image points and explain the symmetry of the result.

## Practice

1. Reflect a triangle across the $x$-axis.
2. Rotate a point $90^\circ$ counterclockwise about the origin.
3. Determine image coordinates after two transformations.

## Art and Design Connections

- Photograph real conics in architecture (arches, spotlights, domes) and classify each as parabola, ellipse, or hyperbola.
- Design a typography poster using ellipse and parabola guides to control letter curvature and spacing.
- Create a gallery floor plan that uses translated and reflected conic motifs for wayfinding graphics.

## Creative Assignment

### Creative Assignment for this Chapter

No late work is accepted. The homework assignments are given for you to showcase your creativity. You must turn in unique work (created by you).

Your homework submissions will also give you the opportunity to receive extra credit on exams!

**ALWAYS SUBMIT THROUGH THE PADLET (ONLY).**
The homework done by you and your classmates will be shown in a Padlet. You can show a picture or pictures or a video of what you create.

Make sure you put your full name on the padlet post with your creative homework before the deadline.

You will be looking through what everyone has done and vote for your favorite (as part of your grade). During each module, you will receive a course announcement (which is also sent to your FIT Email) that will ask you to vote for your favorite through a Google Form. Voting is part of the grade! You will have multiple days to vote. If you do not vote on a creative homework assignment within the given time frame you will lose one point of your creative homework assignment grade.

You cannot vote for yourself. Each winning assignment gets +1 on the next exam. So, in the first couple homework assignments the winners will get the points on the midterm. After the midterm, if you win then it will go towards your final exam grade.

How the grading on these creative hw assignments work: You can see my grading rubric right [HERE](https://docs.google.com/document/d/1XxYusEMatYQcfNlGPoCyZbbxzbZ3G3FegVa6Zd4w5RE/edit?usp=sharing). There should be no surprises with grading on anything in this course. Please take the time to carefully read the directions and ask me a question if you are confused about what the assignment is asking. If you did not complete an assignment by the deadline it receives NO CREDIT.

Sometimes students will be awarded +.25, +.5, +.75, or +1 on these assignments by me! This happens for many of the creative homework assignments that show lots of effort. These little values add up so give creative homework your best shot. These extra values go on your exams.

If a student asks for extra credit to help their grade, this is one major area to do so!

### Examples and More Information

* See the module folder on our course site for examples that would get credit and bonus for this creative homework assignment.
* For information on how these assignments work; the grading rubric; and the voting you can look in Chapter 9 of this textbook or many places on our course site!
* The more effort you put in for these assignments, the more bonus you get on exams. It helps if you write how long it took you to complete your work and how you created your assignment.

## Exercises

### Exercises for this Chapter

* Make sure you are logged into your FIT Google account or else you will not view the link below.
* Once you have your answers, submit them carefully through our course site on Brightspace by the deadline.
- [Conic Sections Exercises (Google Doc)](https://docs.google.com/document/d/10OcsnlokYO7z1wRT5nPUskJUs1u3-0VP55SpWxNbqMQ/edit?usp=sharing)

### More Exercises

## Further Reading and Interactive Activities
